# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Meta
mod_name=TC Utility
mod_group=com.troblecodings
mod_version=1.3.1

# Minecraft
minecraft_version=1.14.4

# Forge
forge_version=28.2.28
loader=Forge

# Java
java_version=8

# Publishing
curseforge_project_id=821776
modrinth_project_id=IdSl9Mvp