# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Meta
mod_id=tcutility
mod_name=TC Utility
mod_group=com.troblecodings
mod_author=Jeronimo
mod_version=1.3.0

# Minecraft
minecraft_version=1.12.2
loader=forge

# Forge
forge_version_main=14
forge_version=14.23.5.2860

# Java
java_version=8

# Publishing
curseforge_project_id=821776
modrinth_project_id=IdSl9Mvp