modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MrTroble/TCUtility/issues"
license="Apache License Version 2.0"

[[mods]]
modId="tcutility"
version="${file.jarVersion}"
displayName="TC Utility"
displayURL="https://troblecodings.com/"
authors="Jeronimo, Luex"
credits="German Immersive Railroading Community"
description="This mod adds a lot of new building and decorative blocks. You can easily add more due to Json-based blockregistration with contentpacks."

[[dependencies.tcutility]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tcutility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
