modLoader="javafml"
loaderVersion="[14,)"
issueTrackerURL="https://github.com/MrTroble/TCUtility/issues"
license="Apache License Version 2.0"

[[mods]]
modId="tcutility"
version="${file.jarVersion}"
displayName="TCUtility"
displayURL="https://troblecodings.com/"
authors="Jeronimo"
credits="German Immersive Railroading Community"
description="This mod adds a lot of new building and decorative blocks. You can easily add more due to Json-based blockregistration with contentpacks."

[[dependencies.tcutility]]
    modId="forge" 
    mandatory=true 
    versionRange="[14,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.tcutility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.12.2]"
    ordering="NONE"
    side="BOTH"
